### ISSUE TITLE
Support for Jupyter notebooks via vim-jukit

### ISSUE THREAD

**Issue by solarider** [justinsgithub/Oh-My-LazyVim#4]
Just came across your project and liking it so far as I'm trying to avoid hours hacking away at my own nvim configs and just want something that works and has a load of support for various plugins included. Even with everything enabled (bar vim-wakatime) my install is nice and fast  - thanks.

It would be good to have decent [Jupyer Notebook](https://jupyter.org/).

There are a few plugins available and the one I'm currently looking at is [vim-jukit](https://github.com/luk400/vim-jukit) - would you be able to add this to your build?

**Comment by justinsgithub** [comment]
Making changes to the structure and will at this plugin by end of next
week, thanks for the feed back!

**Comment by justinsgithub** [comment]
Added
